/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CoachRouteImport } from './routes/_coach'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as CoachIndexRouteImport } from './routes/_coach/index'
import { Route as CoachAdminRouteImport } from './routes/_coach/admin'
import { Route as CoachPuzzlesPuzzleIdRouteImport } from './routes/_coach/puzzles.$puzzleId'
import { Route as CoachPuzzlesNewRouteImport } from './routes/_coach/puzzles.new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEngineMoveRouteImport } from './routes/api/engine/move'

const CoachRoute = CoachRouteImport.update({
  id: '/_coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoachRoute,
} as any)
const CoachAdminRoute = CoachAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => CoachRoute,
} as any)
const CoachPuzzlesPuzzleIdRoute = CoachPuzzlesPuzzleIdRouteImport.update({
  id: '/puzzles/$puzzleId',
  path: '/puzzles/$puzzleId',
  getParentRoute: () => CoachRoute,
} as any)
const CoachPuzzlesNewRoute = CoachPuzzlesNewRouteImport.update({
  id: '/puzzles/new',
  path: '/puzzles/new',
  getParentRoute: () => CoachRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEngineMoveRoute = ApiEngineMoveRouteImport.update({
  id: '/api/engine/move',
  path: '/api/engine/move',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof CoachIndexRoute
  '/credits': typeof CreditsRoute
  '/sign-in': typeof SignInRoute
  '/admin': typeof CoachAdminRoute
  '/puzzles/$puzzleId': typeof CoachPuzzlesPuzzleIdRoute
  '/puzzles/new': typeof CoachPuzzlesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/engine/move': typeof ApiEngineMoveRoute
}
export interface FileRoutesByTo {
  '/credits': typeof CreditsRoute
  '/sign-in': typeof SignInRoute
  '/admin': typeof CoachAdminRoute
  '/': typeof CoachIndexRoute
  '/puzzles/$puzzleId': typeof CoachPuzzlesPuzzleIdRoute
  '/puzzles/new': typeof CoachPuzzlesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/engine/move': typeof ApiEngineMoveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_coach': typeof CoachRouteWithChildren
  '/credits': typeof CreditsRoute
  '/sign-in': typeof SignInRoute
  '/_coach/admin': typeof CoachAdminRoute
  '/_coach/': typeof CoachIndexRoute
  '/_coach/puzzles/$puzzleId': typeof CoachPuzzlesPuzzleIdRoute
  '/_coach/puzzles/new': typeof CoachPuzzlesNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/engine/move': typeof ApiEngineMoveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/credits'
    | '/sign-in'
    | '/admin'
    | '/puzzles/$puzzleId'
    | '/puzzles/new'
    | '/api/auth/$'
    | '/api/engine/move'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/credits'
    | '/sign-in'
    | '/admin'
    | '/'
    | '/puzzles/$puzzleId'
    | '/puzzles/new'
    | '/api/auth/$'
    | '/api/engine/move'
  id:
    | '__root__'
    | '/_coach'
    | '/credits'
    | '/sign-in'
    | '/_coach/admin'
    | '/_coach/'
    | '/_coach/puzzles/$puzzleId'
    | '/_coach/puzzles/new'
    | '/api/auth/$'
    | '/api/engine/move'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CoachRoute: typeof CoachRouteWithChildren
  CreditsRoute: typeof CreditsRoute
  SignInRoute: typeof SignInRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEngineMoveRoute: typeof ApiEngineMoveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_coach': {
      id: '/_coach'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_coach/': {
      id: '/_coach/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_coach/admin': {
      id: '/_coach/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof CoachAdminRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_coach/puzzles/$puzzleId': {
      id: '/_coach/puzzles/$puzzleId'
      path: '/puzzles/$puzzleId'
      fullPath: '/puzzles/$puzzleId'
      preLoaderRoute: typeof CoachPuzzlesPuzzleIdRouteImport
      parentRoute: typeof CoachRoute
    }
    '/_coach/puzzles/new': {
      id: '/_coach/puzzles/new'
      path: '/puzzles/new'
      fullPath: '/puzzles/new'
      preLoaderRoute: typeof CoachPuzzlesNewRouteImport
      parentRoute: typeof CoachRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/engine/move': {
      id: '/api/engine/move'
      path: '/api/engine/move'
      fullPath: '/api/engine/move'
      preLoaderRoute: typeof ApiEngineMoveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CoachRouteChildren {
  CoachAdminRoute: typeof CoachAdminRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CoachPuzzlesPuzzleIdRoute: typeof CoachPuzzlesPuzzleIdRoute
  CoachPuzzlesNewRoute: typeof CoachPuzzlesNewRoute
}

const CoachRouteChildren: CoachRouteChildren = {
  CoachAdminRoute: CoachAdminRoute,
  CoachIndexRoute: CoachIndexRoute,
  CoachPuzzlesPuzzleIdRoute: CoachPuzzlesPuzzleIdRoute,
  CoachPuzzlesNewRoute: CoachPuzzlesNewRoute,
}

const CoachRouteWithChildren = CoachRoute._addFileChildren(CoachRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CoachRoute: CoachRouteWithChildren,
  CreditsRoute: CreditsRoute,
  SignInRoute: SignInRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEngineMoveRoute: ApiEngineMoveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
